import type { Metadata } from "next";
import "./globals.css";

import { Fira_Code } from "next/font/google";

const firacode = Fira_Code({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "<CodeTonic/>",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${firacode.className} bg-green-200 flex justify-center`}
      >
        {children}
      </body>
    </html>
  );
}
