import type { Metadata } from "next";
import "./globals.css";

import { Fira_Code, Poppins } from "next/font/google";

// const firacode = Fira_Code({ subsets: ["latin"] });
const poppins = Poppins({ subsets: ["latin"], weight: ["400", "500", "600"] });

export const metadata: Metadata = {
  title: "<CodeTonic/>",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} text-black flex justify-center overflow-x-hidden`}
      >
        {children}
      </body>
    </html>
  );
}
